<h2 style="text-align: center;">Privacy Policy & Terms of Service</h2>
Pok&eacute;mon Vortex, it's advertisers and affiliates are deeply committed to protecting the privacy of Internet users. Below is information outlining our continued support for the responsible management of consumer information.
<h4>Consumer Information</h4>
During the process of visiting our websites, Pok&eacute;mon Vortex does not collect any personally identifiable information about you such as name, address, or phone number. However, Pok&eacute;mon Vortex does obtain some types of non-personally identifiable information such as the Internet Service Provider you use to connect to the Internet, your browser type, or the type of computer operating system you use (Macintosh or Windows, for example). The information collected by Pok&eacute;mon Vortex is used for the purpose of targeting advertising.
</p>
In some cases, you may voluntarily provide personal information in response to a specific advert (this ad may ask you to fill out a survey or provide your zip code). If this does occur, Pok&eacute;mon Vortex may collect this information on behalf of an advertiser. This information is used by an advertiser to respond to your request. In addition, Pok&eacute;mon Vortex may combine this information with other users' information and review it in an aggregate form to understand the type of individuals who view a specific type of ad or visit a particular kind of website.
<h4>Data Collection</h4>
Pok&eacute;mon Vortex, as well as most sites on the Internet, use "cookies" to enhance your experience on the web. Pok&eacute;mon Vortex cannot use these cookies to personally identify you in any way. What are cookies and why do we use them? A cookie is a piece of data that is provided to you the first time you visit a website. This unique data may later be recovered from your computer. This cookie can help Pok&eacute;mon Vortex ensure that we don't serve you the same ad multiple times, and help our advertisers understand what you like and don't like about their offerings so that they can cater better to your needs the next time you are interested in their products or services. We believe that cookies enhance your Internet experience.
<h4>Limit of Liability</h4>
User agrees that the use of Pok&eacute;mon Vortex's services is entirely at User's own risk. Pok&eacute;mon Vortex's services are provided on an "as is" basis without warranties of any kind, either expressed or implied, constructive, or statutory, including, without limitation, any implied warranties of merchantability, non-infringement or fitness for a particular purpose.
</p>
Pok&eacute;mon Vortex makes no guarantee of availability of service and reserves the right to change, withdraw, suspend, or discontinue any functionality or feature of Pok&eacute;mon Vortex's services. In no event shall Pok&eacute;mon Vortex be liable for any damages, including, without limitation, direct, indirect, incidental, special, consequential, or punitive damages arising out of the use of or inability to use Pok&eacute;mon Vortex's services or any content thereon. This disclaimer applies, without limitation, to any damages or injury, whether for breach of contract, tort, or otherwise, caused by any failure of performance; error; omission; interruption; deletion; defect; delay in operation or transmission; computer virus; file corruption; communication-line failure; network or system outage; or theft, destruction, unauthorized access to, alteration of, or use of any record.
</p>
User agrees to indemnify and hold Pok&eacute;mon Vortex harmless from any loss, liability, claims, damages and expenses, including attorneys fees, arising from or related to the content, use, or deletion of User's Files or use of any other feature or service. This expressly includes:<br />
- User's responsibility for any and all liability arising from the violation or infringement of proprietary rights or copyrights.<br />
- Any defamatory or unlawful material contained within User's Files.
</p>
To ensure the privacy of kids, we do not collect any personally identifiable information from children of any age. Only a user name that they have chosen and information related to the game (such as Pokemon they have, badges earned, etc) is available to other members, unless they wish to share any internet based networking display names with other members. This feature can be turned off or left blank to protect identities.
</p>
Any personal information provided to Pok&eacute;mon Vortex will not be sold or given out.
</p>
Suggestions may be sent to Pok&eacute;mon Vortex, but most will not be reviewed or implemented. Pok&eacute;mon Vortex will not give credit or be liable (monetarily or otherwise) to anyone for any suggestions submitted or implemented.
</p>