<p class="optionsList autowidth"><a href="trade.php" onclick="get('trade.php',''); return false;" class="selected">Trade home</a> | <a href="trade.php?cat=puft" onclick="get('trade.php','cat=puft'); return false;" class="deselected">Select Pokemon to put up for trade</a> | <a href="trade.php?cat=uft" onclick="get('trade.php','cat=uft'); return false;" class="deselected">Pokemon up for trade</a> | <a href="trade.php?cat=offered" onclick="get('trade.php','cat=offered'); return false;" class="deselected">Pokemon you have offered</a><br/><a href="trade.php?cat=notifications" onclick="get('trade.php','cat=notifications'); return false;" class="deselected">Recent trade notifications</a></p>
<?php
if(isset($_REQUEST['type'])){
	include('trade_search.php');
}
?>
<center>
<div style="margin-top:50px;">
<noscript><div class="noticeMsg">This search requires javascript to be turned on, please do so before continuing.</div></noscript>
<script type="text/javascript">
trade_search = function(){
	ex = document.getElementById('type');
	if(ex.value == "Pokemon"){
		document.getElementById('22').style.display = 'none';
		document.getElementById('23').style.display = 'block';
	}
	if(ex.value == "Username"){
		document.getElementById('22').style.display = 'block';
		document.getElementById('23').style.display = 'none';
	}
}
</script><p>Search Trades: <select name="type" id="type" onchange="trade_search();"><option>Pokemon</option><option>Username</option></select></p>
 <div id="22" style="display:none;"><form method="post" onsubmit="get('/trade.php', '', this); disableSubmitButton(this); return false;">
<p><input type="text" name="search" style="margin-top:2px;" /></p>
<p><input type="hidden" name="type" value="Username"><input type="submit" name="find" value="Search" /></p></form></div>


<div id="23" style="display:block;"><form method="post" onsubmit="get('/trade.php', '', this); disableSubmitButton(this); return false;"><p><select name="ptype"><option value="%">All</option><option value="">Normal </option><option value="Dark ">Dark </option><option value="Metallic ">Metallic </option><option value="Mystic ">Mystic </option><option value="Shiny ">Shiny </option><option value="Shadow ">Shadow </option></select> <select name="pokemon"><option>Abomasnow</option><option>Abomasnow (Mega)</option><option>Abra</option><option>Absol</option><option>Absol (Mega)</option><option>Accelgor</option><option>Aegislash (Blade)</option><option>Aegislash (Shield)</option><option>Aerodactyl</option><option>Aerodactyl (Mega)</option><option>Aggron</option><option>Aggron (Mega)</option><option>Aipom</option><option>Alakazam</option><option>Alakazam (Mega)</option><option>Alomomola</option><option>Altaria</option><option>Altaria (Mega)</option><option>Amaura</option><option>Ambipom</option><option>Ampharos</option><option>Ampharos (Mega)</option><option>Amoonguss</option><option>Anorith</option><option>Arbok</option><option>Arcanine</option><option>Arceus</option><option>Arceus (Bug)</option><option>Arceus (Dark)</option><option>Arceus (Dragon)</option><option>Arceus (Electric)</option><option>Arceus (Fairy)</option><option>Arceus (Fighting)</option><option>Arceus (Fire)</option><option>Arceus (Flying)</option><option>Arceus (Ghost)</option><option>Arceus (Grass)</option><option>Arceus (Ground)</option><option>Arceus (Ice)</option><option>Arceus (Poison)</option><option>Arceus (Psychic)</option><option>Arceus (Rock)</option><option>Arceus (Steel)</option><option>Arceus (Unknown)</option><option>Arceus (Water)</option><option>Archen</option><option>Archeops</option><option>Ariados</option><option>Armaldo</option><option>Aromatisse</option><option>Aron</option><option>Articuno</option><option>Audino</option><option>Audino (Mega)</option><option>Aurorus</option><option>Avalugg</option><option>Axew</option><option>Azelf</option><option>Azumarill</option><option>Azurill</option>

<option>Bagon</option><option>Baltoy</option><option>Banette</option><option>Banette (Mega)</option><option>Barbaracle</option><option>Barboach</option><option>Basculin (Blue Stripe)</option><option>Basculin (Red Stripe)</option><option>Bastiodon</option><option>Bayleef</option><option>Beartic</option><option>Beautifly</option><option>Beedrill</option><option>Beedrill (Mega)</option><option>Beheeyem</option><option>Beldum</option><option>Bellossom</option><option>Bellsprout</option><option>Bergmite</option><option>Bibarel</option><option>Bidoof</option><option>Binacle</option><option>Bisharp</option><option>Blastoise</option><option>Blastoise (Mega)</option><option>Blaziken</option><option>Blaziken (Mega)</option><option>Blissey</option><option>Blitzle</option><option>Boldore</option><option>Bonsly</option><option>Bouffalant</option><option>Braviary</option><option>Braixen</option><option>Breloom</option><option>Bronzong</option><option>Bronzor</option><option>Budew</option><option>Buizel</option><option>Bulbasaur</option><option>Buneary</option><option>Bunnelby</option><option>Burmy (Plant)</option><option>Burmy (Sand)</option><option>Burmy (Steel)</option><option>Butterfree</option>

<option>Cacnea</option><option>Cacturne</option><option>Camerupt</option><option>Camerupt (Mega)</option><option>Carbink</option><option>Carracosta</option><option>Carnivine</option><option>Carvanha</option><option>Cascoon</option><option>Castform</option><option>Castform (Fire)</option><option>Castform (Ice)</option><option>Castform (Water)</option><option>Caterpie</option><option>Caterpie (Christmas)</option><option>Celebi</option><option>Celebi (Eternal)</option><option>Chandelure</option><option>Chansey</option><option>Charizard</option><option>Charizard (Mega X)</option><option>Charizard (Mega Y)</option><option>Charmander</option><option>Charmeleon</option><option>Chatot</option><option>Cherrim (Non Sunny)</option><option>Cherrim (Sunny)</option><option>Cherubi</option><option>Chesnaught</option><option>Chespin</option><option>Chikorita</option><option>Chimchar</option><option>Chimecho</option><option>Chinchou</option><option>Chingling</option><option>Cinccino</option><option>Clamperl</option><option>Clauncher</option><option>Clawitzer</option><option>Claydol</option><option>Clefable</option><option>Clefairy</option><option>Cleffa</option><option>Cloyster</option><option>Cobalion</option><option>Cofagrigus</option><option>Combee</option><option>Combusken</option><option>Conkeldurr</option><option>Corphish</option><option>Corsola</option><option>Cottonee</option><option>Cradily</option><option>Cranidos</option><option>Crawdaunt</option><option>Cresselia</option><option>Croagunk</option><option>Crobat</option><option>Croconaw</option><option>Crustle</option><option>Cryogonal</option><option>Cubchoo</option><option>Cubone</option><option>Cyndaquil</option>

<option>Darkrai</option><option>Darkrown</option><option>Darmanitan</option><option>Darmanitan (Zen Mode)<option>Darumaka</option><option>Dedenne</option><option>Deerling (Autumn)</option><option>Deerling (Spring)</option><option>Deerling (Summer)</option><option>Deerling (Winter)</option><option>Deino</option><option>Delcatty</option><option>Delibird</option><option>Deoxys</option><option>Deoxys (Attack)</option><option>Deoxys (Defense)</option><option>Deoxys (Speed)</option><option>Delphox</option><option>Dewgong</option><option>Dewott</option><option>Dialga</option><option>Diancie</option><option>Diancie (Mega)</option><option>Diggersby</option><option>Diglett</option><option>Ditto</option><option>Dodrio</option><option>Doduo</option><option>Donphan</option><option>Doublade</option><option>Dragalge</option><option>Dragonair</option><option>Dragonite</option><option>Drapion</option><option>Dratini</option><option>Dratinice</option><option>Dratinilic</option><option>Dratinire</option><option>Drifblim</option><option>Drifloon</option><option>Drilbur</option><option>Drowzee</option><option>Druddigon</option><option>Ducklett</option><option>Dugtrio</option><option>Dunsparce</option><option>Duosion</option><option>Durant</option><option>Dusclops</option><option>Dusknoir</option><option>Duskull</option><option>Dustox</option><option>Dwebble</option>

<option>Eelektrik</option><option>Eelektross</option><option>Eevee</option><option>Ekans</option><option>Electabuzz</option><option>Electivire</option><option>Electrike</option><option>Electrode</option><option>Elekid</option><option>Elgyem</option><option>Emboar</option><option>Emolga</option><option>Empoleon</option><option>Entei</option><option>Escavalier</option><option>Espeon</option><option>Espurr</option><option>Excadrill</option><option>Exeggcute</option><option>Exeggutor</option><option>Exploud</option>

<option>Farfetchd</option><option>Fearow</option><option>Feebas</option><option>Fennekin</option><option>Feraligatr</option><option>Ferroseed</option><option>Ferrothorn</option><option>Finneon</option><option>Flaffy</option><option>Flabebe (Blue)</option><option>Flabebe (Orange)</option><option>Flabebe (Red)</option><option>Flabebe (White)</option><option>Flabebe (Yellow)</option><option>Flareon</option><option>Fletchinder</option><option>Fletchling</option><option>Floatzel</option><option>Floette (Blue)</option><option>Floette (Eternal)</option><option>Floette (Orange)</option><option>Floette (Red)</option><option>Floette (White)</option><option>Floette (Yellow)</option><option>Florges (Blue)</option><option>Florges (Orange)</option><option>Florges (Red)</option><option>Florges (White)</option><option>Florges (Yellow)</option><option>Flygon</option><option>Foongus</option><option>Forretress</option><option>Fraxure</option><option>Frillish</option><option>Froakie</option><option>Frogadier</option><option>Froslass</option><option>Furfrou</option><option>Furfrou (Dandy)</option><option>Furfrou (Deputante)</option><option>Furfrou (Diamond)</option><option>Furfrou (Heart)</option><option>Furfrou (Kabuki)</option><option>Furfrou (La Reine)</option><option>Furfrou (Matron)</option><option>Furfrou (Pharaoh)</option><option>Furfrou (Star)</option><option>Furret</option>

<option>Gabite</option><option>Gallade</option><option>Gallade (Mega)</option><option>Galvantula</option><option>Garbodor</option><option>Garchomp</option><option>Garchomp (Mega)</option><option>Gardevoir</option><option>Gardevoir (Mega)</option><option>Gastly</option><option>Gastrodon (East)</option><option>Gastrodon (West)</option><option>Genesect</option><option>Genesect (Aqua)</option><option>Genesect (Blaze)</option><option>Genesect (Ice)</option><option>Genesect (Lightning)</option><option>Gengar</option><option>Gengar (Mega)</option><option>Geodude</option><option>Gible</option><option>Gigalith</option><option>Girafarig</option><option>Giratina</option><option>Giratina (Origin)</option><option>Glaceon</option><option>Glalie</option><option>Glalie (Mega)</option><option>Glameow</option><option>Gligar</option><option>Gliscor</option><option>Gloom</option><option>Gogoat</option><option>Golbat</option><option>Goldeen</option><option>Golduck</option><option>Golem</option><option>Golett</option><option>Golurk</option><option>Goodra</option><option>Goomy</option><option>Gorebyss</option><option>Gothita</option><option>Gothitelle</option><option>Gothorita</option><option>Gourgeist (Average)</option><option>Gourgeist (Large)</option><option>Gourgeist (Small)</option><option>Gourgeist (Super)</option><option>Granbull</option><option>Graveler</option><option>Greninja</option><option>Grimer</option><option>Grotle</option><option>Groudon</option><option>Groudon (Primal)</option><option>Grovyle</option><option>Growlithe</option><option>Grumpig</option><option>Gulpin</option><option>Gurdurr</option><option>Gyarados</option><option>Gyarados (Mega)</option>

<option>Happiny</option><option>Hariyama</option><option>Haunter</option><option>Hawlucha</option><option>Haxorus</option><option>Heatmor</option><option>Heatran</option><option>Heliolisk</option><option>Helioptile</option><option>Heracross</option><option>Heracross (Mega)</option><option>Herdier</option><option>Hippopotas</option><option>Hippowdon</option><option>Hitmonchan</option><option>Hitmonlee</option><option>Hitmontop</option><option>Ho-oh</option><option>Honchkrow</option><option>Honedge</option><option>Hoopa</option><option>Hoopa (Unbound)</option><option>Hoothoot</option><option>Hoppip</option><option>Horsea</option><option>Houndoom</option><option>Houndoom (Mega)</option><option>Houndour</option><option>Huntail</option><option>Hydreigon</option><option>Hypno</option>

<option>Igglybuff</option><option>Illumise</option><option>Infernape</option><option>Inkay</option><option>Ivysaur</option>

<option>Jellicent</option><option>Jigglypuff</option><option>Jirachi</option><option>Jolteon</option><option>Joltik</option><option>Jumpluff</option><option>Jynx</option>

<option>Kabuto</option><option>Kabutops</option><option>Kadabra</option><option>Kakuna</option><option>Kangaskhan</option><option>Kangaskhan (Mega)</option><option>Karrablast</option><option>Kecleon</option><option>Keldeo</option><option>Keldeo (Resolution)</option><option>Kingdra</option><option>Kingler</option><option>Kirlia</option><option>Klang</option><option>Klefki</option><option>Klink</option><option>Klinklang</option><option>Koffing</option><option>Krabby</option><option>Kricketot</option><option>Kricketune</option><option>Krokorok</option><option>Krookodile</option><option>Kyogre</option><option>Kyogre (Primal)</option><option>Kyurem</option><option>Kyurem (Black)</option><option>Kyurem (White)</option>

<option>Lairon</option><option>Lampent</option><option>Landorus</option><option>Landorus (Therian)</option><option>Lanturn</option><option>Lapras</option><option>Larvesta</option><option>Larvitar</option><option>Latias</option><option>Latias (Mega)</option><option>Latios</option><option>Latios (Mega)</option><option>Leafeon</option><option>Leavanny</option><option>Ledian</option><option>Ledyba</option><option>Lickilicky</option><option>Lickitung</option><option>Liepard</option><option>Lileep</option><option>Lilligant</option><option>Lillipup</option><option>Linoone</option><option>Litwick</option><option>Litleo</option><option>Lombre</option><option>Lopunny</option><option>Lopunny (Mega)</option><option>Lotad</option><option>Loudred</option><option>Lucario</option><option>Lucario (Mega)</option><option>Ludicolo</option><option>Lugia</option><option>Lumineon</option><option>Lunatone</option><option>Luvdisc</option><option>Luxio</option><option>Luxray</option>

<option>Machamp</option><option>Machoke</option><option>Machop</option><option>Magby</option><option>Magcargo</option><option>Magikarp</option><option>Magmar</option><option>Magmortar</option><option>Magnemite</option><option>Magneton</option><option>Magnezone</option><option>Makuhita</option><option>Malamar</option><option>Mamoswine</option><option>Manaphy</option><option>Mandibuzz</option><option>Manectric</option><option>Manectric (Mega)</option><option>Mankey</option><option>Mantine</option><option>Mantyke</option><option>Maractus</option><option>Mareep</option><option>Marill</option><option>Marowak</option><option>Marshtomp</option><option>Masquerain</option><option>Mawile</option><option>Mawile (Mega)</option><option>Medicham</option><option>Medicham (Mega)</option><option>Meditite</option><option>Meganium</option><option>Meloetta (Aria)</option><option>Meloetta (Pirouette)</option><option>Meowstic (F)</option><option>Meowstic (M)</option><option>Meowth</option><option>Mesprit</option><option>Metagross</option><option>Metagross (Mega)</option><option>Metang</option><option>Metapod</option><option>Mew</option><option>Mewtwo</option><option>Mewtwo (Armor)</option><option>Mewtwo (Mega X)</option><option>Mewtwo (Mega Y)</option><option>Mienfoo</option><option>Mienshao</option><option>Mightyena</option><option>Milotic</option><option>Miltank</option><option>Mime Jr.</option><option>Minccino</option><option>Minun</option><option>Misdreavus</option><option>Mismagius</option><option>Missingno.</option><option>Moltres</option><option>Monferno</option><option>Mothim</option><option>Mr. Mime</option><option>Mudkip</option><option>Muk</option><option>Munchlax</option><option>Munna</option><option>Murkrow</option><option>Musharna</option>

<option>Natu</option><option>Nidoking</option><option>Nidoqueen</option><option>Nidoran (F)</option><option>Nidoran (M)</option><option>Nidorina</option><option>Nidorino</option><option>Nincada</option><option>Ninetales</option><option>Ninjask</option><option>Noctowl</option><option>Noibat</option><option>Noivern</option><option>Nosepass</option><option>Numel</option><option>Nuzleaf</option>

<option>Octillery</option><option>Oddish</option><option>Omanyte</option><option>Omastar</option><option>Onix</option><option>Oshawott</option>

<option>Pachirisu</option><option>Palkia</option><option>Palpitoad</option><option>Pancham</option><option>Pangoro</option><option>Paras</option><option>Parasect</option><option>Patrat</option><option>Panpour</option><option>Pansage</option><option>Pansear</option><option>Pawniard</option><option>Pelipper</option><option>Persian</option><option>Petilil</option><option>Phanpy</option><option>Phantump</option><option>Phione</option><option>Pichu</option><option>Pichu (Notched)</option><option>Pidgeot</option><option>Pidgeot (Mega)</option><option>Pidgeotto</option><option>Pidgey</option><option>Pidove</option><option>Pignite</option><option>Pikachu</option><option>Pikachu (Belle)</option><option>Pikachu (Libre)</option><option>Pikachu (Ph. D.)</option><option>Pikachu (Pop Star)</option><option>Pikachu (Rock Star)</option><option>Piloswine</option><option>Pineco</option><option>Pinsir</option><option>Pinsir (Mega)</option><option>Piplup</option><option>Plusle</option><option>Politoed</option><option>Poliwag</option><option>Poliwhirl</option><option>Poliwrath</option><option>Ponyta</option><option>Poochyena</option><option>Porygon</option><option>Porygon-Z</option><option>Porygon2</option><option>Primeape</option><option>Prinplup</option><option>Probopass</option><option>Psyduck</option><option>Pumpkaboo (Average)</option><option>Pumpkaboo (Large)</option><option>Pumpkaboo (Small)</option><option>Pumpkaboo (Super)</option><option>Pupitar</option><option>Purrloin</option><option>Purugly</option><option>Pyroar</option>

<option>Quagsire</option><option>Quilladin</option><option>Quilava</option><option>Qwilfish</option>

<option>Raichu</option><option>Raikou</option><option>Ralts</option><option>Rampardos</option><option>Rapidash</option><option>Raticate</option><option>Rattata</option><option>Rayquaza</option><option>Rayquaza (Mega)</option><option>Regice</option><option>Regigigas</option><option>Regirock</option><option>Registeel</option><option>Relicanth</option><option>Remoraid</option><option>Reshiram</option><option>Reuniclus</option><option>Rhydon</option><option>Rhyhorn</option><option>Rhyperior</option><option>Riolu</option><option>Roggenrola</option><option>Roselia</option><option>Roserade</option><option>Rotom</option><option>Rotom (Cut)</option><option>Rotom (Frost)</option><option>Rotom (Halloween)</option><option>Rotom (Heat)</option><option>Rotom (Spin)</option><option>Rotom (Wash)</option><option>Rufflet</option>

<option>Sableye</option><option>Sableye (Mega)</option><option>Salamence</option><option>Salamence (Mega)</option><option>Samurott</option><option>Sandile</option><option>Sandshrew</option><option>Sandslash</option><option>Sawk</option><option>Sawsbuck (Autumn)</option><option>Sawsbuck (Spring)</option><option>Sawsbuck (Summer)</option><option>Sawsbuck (Winter)</option><option>Scatterbug</option><option>Sceptile</option><option>Sceptile (Mega)</option><option>Scizor</option><option>Scizor (Mega)</option><option>Scolipede</option><option>Scrafty</option><option>Scraggy</option><option>Scyther</option><option>Seadra</option><option>Seaking</option><option>Sealeo</option><option>Seedot</option><option>Seel</option><option>Seismitoad</option><option>Sentret</option><option>Serperior</option><option>Servine</option><option>Seviper</option><option>Sewaddle</option><option>Sharpedo</option><option>Sharpedo (Mega)</option><option>Shaymin</option><option>Shaymin (Sky)</option><option>Shedinja</option><option>Shelgon</option><option>Shellder</option><option>Shellos (East)</option><option>Shellos (West)</option><option>Shelmet</option><option>Shieldon</option><option>Shiftry</option><option>Shiftry</option><option>Shinx</option><option>Shroomish</option><option>Shuckle</option><option>Shuppet</option><option>Sigilyph</option><option>Silcoon</option><option>Simipour</option><option>Simisage</option><option>Simisear</option><option>Skarmory</option><option>Skiddo</option><option>Skiploom</option><option>Skitty</option><option>Skorupi</option><option>Skrelp</option><option>Skuntank</option><option>Slaking</option><option>Slakoth</option><option>Sliggoo</option><option>Slowbro</option><option>Slowbro (Mega)</option><option>Slowking</option><option>Slowpoke</option><option>Slugma</option><option>Slurpuff</option><option>Smeargle</option><option>Smoochum</option><option>Sneasel</option><option>Snivy</option><option>Snorlax</option><option>Snorunt</option><option>Snover</option><option>Snubbull</option><option>Solosis</option><option>Solrock</option><option>Spearow</option><option>Spewpa</option><option>Spheal</option><option>Spinarak</option><option>Spinda</option><option>Spiritomb</option><option>Spoink</option><option>Spritzee</option><option>Squirtle</option><option>Stantler</option><option>Staraptor</option><option>Staravia</option><option>Starly</option><option>Starmie</option><option>Staryu</option><option>Steelix</option><option>Steelix (Mega)</option><option>Stoutland</option><option>Stunfisk</option><option>Stunky</option><option>Sudowoodo</option><option>Suicune</option><option>Sunflora</option><option>Sunkern</option><option>Surskit</option><option>Swablu</option><option>Swadloon</option><option>Swalot</option><option>Swampert</option><option>Swampert (Mega)</option><option>Swanna</option><option>Swellow</option><option>Swinub</option><option>Swirlix</option><option>Swoobat</option><option>Sylveon</option>

<option>Taillow</option><option>Talonflame</option><option>Tangela</option><option>Tangrowth</option><option>Tauros</option><option>Teddiursa</option><option>Tentacool</option><option>Tentacruel</option><option>Tepig</option><option>Terrakion</option><option>Throh</option><option>Thundurus</option><option>Thundurus (Therian)</option><option>Timburr</option><option>Tirtouga</option><option>Togekiss</option><option>Togepi</option><option>Togetic</option><option>Torchic</option><option>Torkoal</option><option>Tornadus</option><option>Tornadus (Therian)</option><option>Torterra</option><option>Totodile</option><option>Toxicroak</option><option>Trapinch</option><option>Tranquill</option><option>Treecko</option><option>Tropius</option><option>Trubbish</option><option>Turtwig</option><option>Tympole</option><option>Tynamo</option><option>Typhlosion</option><option>Tyranitar</option><option>Tyranitar (Mega)</option><option>Tyrantrum</option><option>Tyrogue</option><option>Tyrunt</option>

<option>Umbreon</option><option>Unown (A)</option><option>Unown (B)</option><option>Unown (C)</option><option>Unown (D)</option><option>Unown (E)</option><option>Unown (Ex)</option><option>Unown (F)</option><option>Unown (G)</option><option>Unown (H)</option><option>Unown (I)</option><option>Unown (J)</option><option>Unown (K)</option><option>Unown (L)</option><option>Unown (M)</option><option>Unown (N)</option><option>Unown (O)</option><option>Unown (P)</option><option>Unown (Q)</option><option>Unown (Qm)</option><option>Unown (R)</option><option>Unown (S)</option><option>Unown (T)</option><option>Unown (U)</option><option>Unown (V)</option><option>Unown (W)</option><option>Unown (X)</option><option>Unown (Y)</option><option>Unown (Z)</option><option>Unfezant</option><option>Ursaring</option><option>Uxie</option>

<option>Vanillish</option><option>Vanillite</option><option>Vanilluxe</option><option>Vaporeon</option><option>Venipede</option><option>Venomoth</option><option>Venonat</option><option>Venusaur</option><option>Venusaur (Mega)</option><option>Vespiquen</option><option>Vibrava</option><option>Victini</option><option>Victreebel</option><option>Vigoroth</option><option>Vileplume</option><option>Virizion</option><option>Vivillon (Archipelago)</option><option>Vivillon (Continental)</option><option>Vivillon (Elegant)</option><option>Vivillon (Fancy)</option><option>Vivillon (Garden)</option><option>Vivillon (High Plains)</option><option>Vivillon (Icy Snow)</option><option>Vivillon (Jungle)</option><option>Vivillon (Marine)</option><option>Vivillon (Meadow)</option><option>Vivillon (Modern)</option><option>Vivillon (Monsoon)</option><option>Vivillon (Ocean)</option><option>Vivillon (Pokeball)</option><option>Vivillon (Polar)</option><option>Vivillon (River)</option><option>Vivillon (Sandstorm)</option><option>Vivillon (Savanna)</option><option>Vivillon (Sun)</option><option>Vivillon (Tundra)</option><option>Volbeat</option><option>Volcanion</option><option>Volcarona</option><option>Voltorb</option><option>Vullaby</option><option>Vulpix</option>

<option>Wailmer</option><option>Wailord</option><option>Walrein</option><option>Wartortle</option><option>Watchog</option><option>Weavile</option><option>Weedle</option><option>Weepinbell</option><option>Weezing</option><option>Whimsicott</option><option>Whirlipede</option><option>Whiscash</option><option>Whismur</option><option>Wigglytuff</option><option>Wingull</option><option>Wobbuffet</option><option>Woobat</option><option>Wooper</option><option>Wormadam (Plant)</option><option>Wormadam (Sand)</option><option>Wormadam (Steel)</option><option>Wurmple</option><option>Wynaut</option>

<option>Xatu</option><option>Xerneas (Active)</option><option>Xerneas (Neutral)</option>

<option>Yamask</option><option>Yanma</option><option>Yanmega</option><option>Yveltal</option>

<option>Zangoose</option><option>Zapdos</option><option>Zebstrika</option><option>Zekrom</option><option>Zigzagoon</option><option>Zoroark</option><option>Zorua</option><option>Zubat</option><option>Zweilous</option><option>Zygarde</option></select></p>
<p><input type="hidden" name="type" value="Pokemon"><input type="submit" name="find" value="Search" /></p></form></div></center>
